package rocks.teagantotally.heartofgoldnotifications.domain.framework.event.mqtt

import rocks.teagantotally.heartofgoldnotifications.domain.framework.UseCaseWithParameter
import rocks.teagantotally.heartofgoldnotifications.domain.usecases.mqtt.connected.Connection

interface MqttConnectedUseCase : UseCaseWithParameter<Connection>