package rocks.teagantotally.heartofgoldnotifications.domain.framework.event.config.pre

import rocks.teagantotally.heartofgoldnotifications.domain.models.configs.ConnectionConfiguration
import rocks.teagantotally.heartofgoldnotifications.domain.models.events.ClientConfigurationChangedEvent

interface PreConnectionConfigurationChangedUseCase :
    PreConfigurationChangedUseCase<ClientConfigurationChangedEvent, ConnectionConfiguration>