package rocks.teagantotally.heartofgoldnotifications.domain.framework.managers

import rocks.teagantotally.heartofgoldnotifications.domain.models.configs.ConnectionConfiguration

interface ConnectionConfigManager : ConfigManager<ConnectionConfiguration>