package rocks.teagantotally.heartofgoldnotifications.domain.framework.managers

import rocks.teagantotally.heartofgoldnotifications.domain.models.configs.NotificationConfiguration

interface NotificationConfigManager : ConfigManager<NotificationConfiguration>