package rocks.teagantotally.heartofgoldnotifications.domain.framework.event.config.post

import rocks.teagantotally.heartofgoldnotifications.domain.models.configs.ConnectionConfiguration
import rocks.teagantotally.heartofgoldnotifications.domain.models.events.ClientConfigurationChangedEvent

interface PostConnectionConfigurationChangedUseCase :
    PostConfigurationChangedUseCase<ClientConfigurationChangedEvent, ConnectionConfiguration>